[project]
name = "sdr"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Matthew Perry", email = "perrygeo@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "matplotlib>=3.11.1",
    "numpy>=2.5.3",
    "pymodes>=3.6.0",
    "pyqt5>=5.15.11",
    "pyrtlsdr>=0.5.0",
]

[project.scripts]
sdr = "sdr:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
